#!/usr/bin/env bash
# ── pi-clone-to-nvme.sh ─────────────────────────────────────────────
# Runs on Raspberry Pi 5 when booted from USB.
# Clones the running system (boot + root) from USB to NVMe SSD,
# then configures the Pi to boot from NVMe and powers off.
#
# After this script runs, you remove the USB and power on.
# The Pi boots from NVMe, and the normal k3s first-boot script runs.
set -euo pipefail

LOG_TAG="pi-clone-nvme"
log() { echo "[$(date -Is)] $*" | tee -a /var/log/k3s-bootstrap.log; logger -t "$LOG_TAG" "$*"; }

# ── Only run on Pi (ARM64) ──────────────────────────────────────────
ARCH=$(uname -m)
if [[ "$ARCH" != "aarch64" ]]; then
    log "Not an ARM64 system ($ARCH). Skipping NVMe clone."
    exit 0
fi

# ── Check for NVMe ──────────────────────────────────────────────────
NVME_DEV="/dev/nvme0n1"
if [[ ! -b "$NVME_DEV" ]]; then
    log "ERROR: No NVMe device found at $NVME_DEV"
    log "Make sure the NVMe M.2 HAT is connected and the SSD is seated properly."
    exit 1
fi

# ── Detect if already booted from NVMe ──────────────────────────────
ROOT_SOURCE=$(findmnt -n -o SOURCE /)
if [[ "$ROOT_SOURCE" == *"nvme"* ]]; then
    log "Already booted from NVMe ($ROOT_SOURCE). Skipping clone."
    touch /opt/k3s-bootstrap/.nvme-clone-done
    exit 0
fi

log "Booted from USB ($ROOT_SOURCE). Starting clone to NVMe ($NVME_DEV)..."

# ── Find the USB partitions we booted from ──────────────────────────
USB_ROOT_DEV=$(findmnt -n -o SOURCE /)
USB_BOOT_DEV=$(findmnt -n -o SOURCE /boot/firmware 2>/dev/null || true)

if [[ -z "$USB_BOOT_DEV" ]]; then
    # Try alternative mount points
    USB_BOOT_DEV=$(findmnt -n -o SOURCE /boot 2>/dev/null || true)
fi

log "USB root: $USB_ROOT_DEV"
log "USB boot: ${USB_BOOT_DEV:-not found}"

# ── Partition the NVMe ──────────────────────────────────────────────
log "Partitioning NVMe ($NVME_DEV)..."

# Install required tools if missing
apt-get update -qq && apt-get install -y -qq parted rsync dosfstools e2fsprogs >/dev/null 2>&1 || true

# Wipe and partition
wipefs -af "$NVME_DEV" >/dev/null 2>&1
parted -s "$NVME_DEV" mklabel gpt
parted -s "$NVME_DEV" mkpart "boot" fat32 1MiB 513MiB
parted -s "$NVME_DEV" set 1 boot on
parted -s "$NVME_DEV" mkpart "root" ext4 513MiB 100%

sleep 2
partprobe "$NVME_DEV" 2>/dev/null || true
sleep 2

NVME_BOOT="${NVME_DEV}p1"
NVME_ROOT="${NVME_DEV}p2"

# Format
log "Formatting NVMe partitions..."
mkfs.fat -F 32 -n "PI_BOOT" "$NVME_BOOT"
mkfs.ext4 -F -L "PI_ROOT" "$NVME_ROOT"

# ── Clone root filesystem ───────────────────────────────────────────
CLONE_ROOT="/tmp/nvme-root"
CLONE_BOOT="/tmp/nvme-boot"
mkdir -p "$CLONE_ROOT" "$CLONE_BOOT"

mount "$NVME_ROOT" "$CLONE_ROOT"
mount "$NVME_BOOT" "$CLONE_BOOT"

log "Cloning root filesystem to NVMe (this may take several minutes)..."
rsync -aAXH --info=progress2 \
    --exclude='/tmp/*' \
    --exclude='/proc/*' \
    --exclude='/sys/*' \
    --exclude='/dev/*' \
    --exclude='/run/*' \
    --exclude='/mnt/*' \
    --exclude='/media/*' \
    --exclude='/lost+found' \
    / "$CLONE_ROOT/"

# Create necessary directories
mkdir -p "$CLONE_ROOT"/{proc,sys,dev,run,tmp,mnt,media}
chmod 1777 "$CLONE_ROOT/tmp"

# Clone boot partition
if [[ -n "$USB_BOOT_DEV" ]]; then
    log "Cloning boot partition to NVMe..."
    rsync -aAXH /boot/firmware/ "$CLONE_BOOT/" 2>/dev/null || \
    rsync -aAXH /boot/ "$CLONE_BOOT/" 2>/dev/null || true
else
    log "No separate boot partition found, copying /boot..."
    rsync -aAXH /boot/ "$CLONE_BOOT/" 2>/dev/null || true
fi

# ── Update UUIDs / fstab on the NVMe clone ──────────────────────────
NVME_ROOT_UUID=$(blkid -s UUID -o value "$NVME_ROOT")
NVME_BOOT_UUID=$(blkid -s UUID -o value "$NVME_BOOT")
NVME_ROOT_PARTUUID=$(blkid -s PARTUUID -o value "$NVME_ROOT")

log "NVMe root UUID: $NVME_ROOT_UUID"
log "NVMe boot UUID: $NVME_BOOT_UUID"

# Update fstab
cat > "${CLONE_ROOT}/etc/fstab" <<FSTAB
# /etc/fstab — generated by pi-clone-to-nvme.sh
UUID=${NVME_ROOT_UUID}  /               ext4  defaults,noatime  0  1
UUID=${NVME_BOOT_UUID}  /boot/firmware  vfat  defaults          0  2
FSTAB

# Update cmdline.txt to point to NVMe root
if [[ -f "${CLONE_BOOT}/cmdline.txt" ]]; then
    sed -i "s|root=[^ ]*|root=UUID=${NVME_ROOT_UUID}|" "${CLONE_BOOT}/cmdline.txt"
    sed -i "s|root=PARTUUID=[^ ]*|root=UUID=${NVME_ROOT_UUID}|" "${CLONE_BOOT}/cmdline.txt"
    log "Updated cmdline.txt with NVMe root UUID"
fi

# ── Mark clone as done (on NVMe) so this doesn't run again ─────────
touch "${CLONE_ROOT}/opt/k3s-bootstrap/.nvme-clone-done"

# ── Ensure the first-boot sentinel exists on NVMe ───────────────────
touch "${CLONE_ROOT}/opt/k3s-bootstrap/.first-boot-pending"

# ── Configure Pi to boot from NVMe ──────────────────────────────────
log "Configuring Pi boot order to prefer NVMe..."

# Update EEPROM boot order: NVMe first, then SD, then USB, then network
# Boot order codes: 6=NVMe, 1=SD, 4=USB, 2=Network
if command -v rpi-eeprom-config &>/dev/null; then
    CURRENT_CONFIG=$(rpi-eeprom-config 2>/dev/null || true)
    if [[ -n "$CURRENT_CONFIG" ]]; then
        EEPROM_TMP=$(mktemp)
        echo "$CURRENT_CONFIG" | sed '/BOOT_ORDER/d' > "$EEPROM_TMP"
        echo "BOOT_ORDER=0xf6142" >> "$EEPROM_TMP"  # NVMe → USB → SD → Network → restart
        rpi-eeprom-config --apply "$EEPROM_TMP" 2>/dev/null || \
            warn "Could not update EEPROM boot order. You may need to set it manually."
        rm -f "$EEPROM_TMP"
    fi
else
    log "rpi-eeprom-config not available. You may need to manually set boot order to NVMe."
    log "Run: sudo rpi-eeprom-config --edit   and set BOOT_ORDER=0xf6142"
fi

# ── Sync and unmount ────────────────────────────────────────────────
sync
umount "$CLONE_BOOT" 2>/dev/null || true
umount "$CLONE_ROOT" 2>/dev/null || true
sync

log ""
log "═══════════════════════════════════════════════════════════════"
log "  NVMe clone complete!"
log "  Root: $NVME_ROOT (UUID: $NVME_ROOT_UUID)"
log "  Boot: $NVME_BOOT (UUID: $NVME_BOOT_UUID)"
log ""
log "  Powering off in 10 seconds..."
log "  Remove the USB drive, then power on."
log "  The Pi will boot from NVMe and set up k3s."
log "═══════════════════════════════════════════════════════════════"

sleep 10
poweroff
